# Generated by Django 4.2.1 on 2024-04-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_alter_useraccount_student_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subject_teacher',
        ),
        migrations.AddField(
            model_name='class',
            name='subject_teacher',
            field=models.ManyToManyField(related_name='subject_teachers', to='app_users.teacher'),
        ),
    ]
