# Generated by Django 5.0.4 on 2024-04-11 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
        ('app_users', '0003_remove_class_subject_teacher_class_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_main.subject'),
        ),
    ]
