# Generated by Django 5.0.4 on 2024-04-11 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_useraccount_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lesson_days', models.CharField(max_length=13)),
                ('class_object', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_users.class')),
                ('subject_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.teacher')),
            ],
        ),
    ]
