# Generated by Django 4.2.10 on 2024-04-12 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_remove_lesson_lesson_days_lesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='class_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.class'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
