# Generated by Django 4.2.10 on 2024-04-13 01:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
