# Generated by Django 5.0.2 on 2024-04-18 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0011_alter_homework_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absent', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.student')),
            ],
        ),
    ]
