# Generated by Django 5.0.2 on 2024-04-28 18:07

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0013_alter_attendance_is_absent_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_users.useraccount',),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='type',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('CLASS_ROOM_TEACHER', 'Class Room Teacher')], default='TEACHER', max_length=18),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('lesson', 'student')},
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('class_room_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_room_teacher_messages', to='app_users.classroomteacher')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_messages', to='app_users.parent')),
            ],
        ),
    ]
