# Generated by Django 5.0.2 on 2024-04-28 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_parent_useraccount_is_parent_alter_useraccount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_students', to='app_users.parent'),
        ),
    ]
