# Generated by Django 5.0.2 on 2024-04-28 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_useraccount_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='parent',
            new_name='parent_of',
        ),
    ]
